name: C++

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: deps
      run: sudo apt install build-essential gcc-9 g++-9 cmake libsdl2-dev libglew-dev libfreetype-dev
    - name: gcc
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
    - name: make
      run: make -j4
